### ISSUE TITLE
ValueError: environment passed to supersuit wrapper must either be a gymnasium environment or a pettingzoo environment

### ISSUE THREAD

**Issue by sunsibar** [jypark0/sen#2]
I'm getting the following error:

```
$ python sen/data/gen_reacher.py --env_id ReacherFixedGoal-v0 --rot90=false --env_timelimit 10 --save_path dataset/reacher/ReacherFixedGoal-v0_train2000.h5 --num_episodes 2000 --seed 1
INFO: Making new env: ReacherFixedGoal-v0
Traceback (most recent call last):
  File "sen/data/gen_reacher.py", line 167, in <module>
    generate_dataset(args)
  File "sen/data/gen_reacher.py", line 47, in generate_dataset
    env = observation_lambda_v0(env, lambda x, _: x[50:450, 50:450, ...])
  File ".../.venv/lib/python3.7/site-packages/supersuit/utils/wrapper_chooser.py", line 38, in __call__
    "environment passed to supersuit wrapper must either be a gymnasium environment or a pettingzoo environment"
ValueError: environment passed to supersuit wrapper must either be a gymnasium environment or a pettingzoo environment
```

Could this be a versioning problem? Would it be possible to say which versions of SuperSuit and pettingzoo you were using? 

------------------------------------

Update: It looks like I found a setting that works, with package versions:

opencv-python==3.4.18.65 
pettingzoo==1.23.1
SuperSuit==3.0.0
torch==1.9.1
torchinfo==1.8.0
torchvision==0.10.1

**Comment by jypark0** [comment]
Hi @sunsibar, glad you got it working. I can't recall exactly which version I used as I deleted the environment to make some storage space :-( Any version that works with gym 0.20.0 or 0.21.0 should work.
